#!/usr/bin/env bash
# Script that installs Nginx server on a new Ubuntu machine


apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start
