#!/usr/bin/env bash
# debugging nginx port 80
#Create symbolic link to correct config file to sites enabled

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
