#!/usr/bin/env bash
# This script uses while and if loops
# to print "Best School" 10 times but
# "Hi" on the 9th iteration

count=0
while [ $count -le 10 ]
do
	if [[ $count -eq 9 ]]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$(( count + 1))
done
