#!/usr/bin/env bash
# Script that runs Nginx as the nginx user
service nginx stop
sed -i 's/user\s*[^;]*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*[^;]*;/listen 8080;/g' /etc/nginx/conf.d/default.conf
pkill apache2
service nginx start
