#!/usr/bin/env bash

# script that creates an RSA key pair

key_name='school'
key_bits='4096'
key_pass='betty'

# Generate new SSH key pair
ssh-keygen -t rsa -b $key_bits -C "school" -f "$HOME/.ssh/$key_name" -q -N "$key_pass"

